name: New Release Python + Playwright images

on:
  push:
    paths:
      - .github/actions/version-matrix/**

env:
  LATEST_PYTHON: "3.13"

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - run: bun install
        working-directory: ./.github/actions/version-matrix

      - id: set-matrix
        run: echo "matrix=\"$(bun python)\"" >> $GITHUB_OUTPUT
        working-directory: ./.github/actions/version-matrix


  build:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - run: echo "I am building Python ${{ matrix.python-version }}, playwright ${{ matrix.playwright-version }}"
